name = "ieee_float"
version = "0.2.3"
description = "Gleam library that provides an IEEE 754 compliant float type."
licences = ["MIT"]
repository = { type = "github", user = "richard-viney", repo = "ieee_float" }
links = [
    { title = "Website", href = "https://github.com/richard-viney/ieee_float" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
startest = ">= 0.4.0 and < 1.0.0"
