name = "ieee_float"
description = "Gleam library that provides an IEEE 754 compliant float type."
licences = ["MIT"]
repository = { type = "github", user = "richard-viney", repo = "ieee_float" }
links = [
    { title = "Website", href = "https://github.com/richard-viney/ieee_float" },
]

[dependencies]
gleam_stdlib = ">= 0.41.0 and < 2.0.0"
gleam_erlang = ">= 0.28.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
deno = { allow_read = true }
