name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.0"
          gleam-version: "1.5.0"
          rebar3-version: "3"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: gleam deps download

      - name: Run tests on Erlang target
        run: gleam test

      - name: Run tests on JavaScript target
        run: gleam test --target javascript

      - name: Check code formatting
        run: gleam format --check src test
